version: '2'
services:
    visahipster-app:
        image: visahipster
        external_links:
            - visahipster-postgresql:postgresql
            - visahipster-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/visahipster
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    visahipster-postgresql:
        extends:
            file: postgresql.yml
            service: visahipster-postgresql
    visahipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: visahipster-elasticsearch
